name: Bug Fix Pull Request

description: |
  Please provide a detailed description of the changes made in this pull request. 
  Include any relevant information that helps to understand the context and the 
  purpose of the changes.

issue: |
  Link to the existing issue that this pull request addresses. 
  Use the format: `Fixes #<issue_number>`.

screenshots: |
  If applicable, please add screenshots to help explain the changes made in this pull request.
  You can drag and drop images here or use markdown to include them.