name: 🐞 ABS App Bug Report
description: File a bug/issue and help us improve the Audiobookshelf apps
title: '[Bug]: '
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: 'Thank you for filing a bug report! 🐛'
  - type: markdown
    attributes:
      value: 'Join the [discord server](https://discord.gg/HQgCbd6E75) for questions or if you are not sure about a bug.'
  - type: markdown
    attributes:
      value: '## App Bug Description'
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please help us understand the problem.
      placeholder: Tell us what you see! Include a screenshot or video if applicable.
    validations:
      required: true
  - type: textarea
    id: what-was-expected
    attributes:
      label: What did you expect to happen?
      description: Please help us understand why that should happen.
      placeholder: Tell us what you expected to see! Please help us visualize by including a doodle or screenshot.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce the issue
      description: Please help us understand how we can reliably see the issue.
      placeholder: '1. Go to the library page of a Podcast library and...'
    validations:
      required: true
  - type: markdown
    attributes:
      value: '## App Environment'
  - type: dropdown
    id: app-version
    attributes:
      label: Audiobookshelf App Version
      description: Please ensure your app is up to date. *If you are using a 3rd-party app, please reach out to them directly.*
      multiple: true
      options:
        - Android App - 0.9.63
        - iOS App - 0.9.63
    validations:
      required: true
  - type: textarea
    id: phone-os
    attributes:
      label: Phone OS
      description: What kind of phone are you using? If Android, is it stock or a custom system?
      placeholder: Android 14, iOS 17.4, etc
    validations:
      required: true
  - type: textarea
    id: phone-model
    attributes:
      label: Phone Model
      description: What kind of phone do you have?
      placeholder: Pixel 6, iPhone 14, Samusung Galaxy s23, etc
    validations:
      required: true
  - type: dropdown
    id: install-source
    attributes:
      label: How did you install the ABS app?
      multiple: true
      options:
        - Google Play Store
        - Testflight
        - SideStore
        - Other (List in "Additional Notes")
    validations:
      required: true
  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Anything else you want to add?
      placeholder: 'e.g. I have tried X, Y, and Z.'
