name: 🚀 Feature Request
description: Request a feature/enhancement
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "### [Mobile app features should be requested here](https://github.com/advplyr/audiobookshelf-app/issues/new/choose)."
  - type: markdown
    attributes:
      value: "### Please first search in both issues & discussions for your enhancement."
  - type: dropdown
    id: enhancment-type
    attributes:
      label: Type of enhancement
      options:
        - Server backend
        - Web client frontend
        - Documentation
  - type: textarea
    id: describe
    attributes:
      label: Describe the feature/enhancement
    validations:
      required: true
  - type: textarea
    id: image
    attributes:
      label: Image
      description: Please include relevant images.
      placeholder: This could be a mockup, screenshot, or anything else that helps visualize the feature. If an image is not applicable, please explain why.
    validations:
      required: true
