name: 🚀 Feature Request
description: Request a feature/enhancement
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "#### *Mobile app features should be [requested here](https://github.com/advplyr/audiobookshelf-app/issues/new/choose)*."
  - type: markdown
    attributes:
      value: "## Feature Request Description"
  - type: markdown
    attributes:
      value: "Please first search in both issues & discussions for your enhancement."
  - type: dropdown
    id: enhancment-type
    attributes:
      label: Type of enhancement
      options:
        - Server Backend
        - Web Interface/Frontend
        - Documentation
  - type: textarea
    id: describe
    attributes:
      label: Describe the feature/enhancement
    validations:
      required: true
  - type: textarea
    id: the-why
    attributes:
      label: What is the use case?
      placeholder: Explain the "why" or "use case".
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Current Implementation"
  - type: textarea
    id: current-image
    attributes:
      label: Current Implementation (screenshot)
      description: Please describe how it works now and include a screenshot if applicable.
      placeholder: If an image is not applicable, please explain why.
    validations:
      required: true
  - type: textarea
    id: image
    attributes:
      label: How it should look or work
      description: Please include relevant images.
      placeholder: This could be a mockup, screenshot, or anything else that helps visualize the feature. If an image is not applicable, please explain why.
