name: Close fixed issues on release.
on:
  release:
    types: [published]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Close issues marked as fixed upon a release.
        uses: nichwall/fixed-pending-release@b157b67607e83b8f9efe274ca75b6efc17de0c06
        with:
          label: awaiting-release
          message: ":tada: This issue has now been fixed and is now available in the latest release! Fixed in [${releaseTag}](${releaseUrl}) :tada:"
