name: Close fixed issues on release.
on:
  release:
    types: [published]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Close issues marked as fixed upon a release.
        uses: nichwall/fixed-pending-release@c788dd6c681ac419af47aee4a798fa70a001947e
        with:
          label: awaiting-release
          applyToAll: true
          message: This issue has now been fixed and is available in [${releaseTag}](${releaseUrl}).
